# Generated by Django 6.0.2 on 2026-03-03 04:46

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_coupon_active_coupon_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='used_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateTimeField(default=store.models.default_expiry),
        ),
    ]
